### ISSUE TITLE
Plugin will not load

### ISSUE THREAD

**Issue by grantboxer** [techforwildlife/UAV-Mapping-Missions-for-Litchi-QGIS-Plugin#1]
Not sure if my earlier post was correctly loaded. I am getting this error on QGIS re-start re the Drone Path plugin.

2022-10-01T07:50:02     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\__init__.py", line 35, in classFactory
              from .drone_path import DronePath
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drone_path\drone_path.py", line 34, in 
              from .resources import *
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'drone_path.resources'

**Comment by M-Sravanthi** [comment]
This error has been rectified. You can reinstall the plugin and it should work.
